### ISSUE TITLE
'ScheduledJob' object has no attribute 'all'

### ISSUE THREAD

**Issue by Gyakusetsu** [cunla/django-rqscheduler#26]
**Describe the bug**
Can't delete one job with `admin.delete_model`

**To Reproduce**
1. Go to [scheduledjob](http://localhost:8000/admin/scheduler/scheduledjob/) in Django admin
2. Click on any job
3. Scroll down to bottom
4. Click "Delete"
5. Click "Yes, I'm sure"
6. See error

**Expected behavior**
Delete scheduled job

**Screenshots**
![image](https://user-images.githubusercontent.com/51472970/174791095-537d12bb-3e18-488e-b995-078c31894fc0.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - python version: 3.9.13
 - django version: 4.0.5
 - django-rq version: 2.5.1
 - requirements.txt?: -

**Additional context**
```python

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 2104, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 2141, in _delete_view
    self.delete_model(request, obj)
  File "/usr/local/lib/python3.9/site-packages/scheduler/admin.py", line 68, in delete_model
    for obj in queryset.all().iterator():

Exception Type: AttributeError at /admin/scheduler/scheduledjob/2/delete/
Exception Value: 'ScheduledJob' object has no attribute 'all'
```

**Comment by cunla** [comment]
fixed
